### ISSUE TITLE
Incorrect push gateway /notify unread counts

### ISSUE THREAD

**Issue by stefanceriu** [element-hq/synapse#16904]
We've been receiving more and more reports that application badges are incorrect, showing increasingly larger numbers no matter what actions the users take.

I have debugged this on my own device and can confirm that the count is coming in the [push notification payload](https://spec.matrix.org/v1.9/push-gateway-api/#post_matrixpushv1notify) from the backend. I tried manually marking all rooms as read, leaving rooms, new sessions and everything else I could think of, nothing budges it downwards. 

Most recent conversation around this happened starting [here](https://matrix.to/#/!PYmTIzCXFFOiozouAk:matrix.org/$fR4fXAFYHQfOSPhXoQNP-2-BppiVQ6fy40FB6RgIqlY?via=matrix.org&via=element.io&via=one.ems.host) where Ben found that 

>I've got a 5 stuck on my EI and looking at `event_push_summary` I've got 5 rows for 5 different rooms with notif_count=1 (no rows in `event_push_actions` for those 5 room ids). If I'm driving the admin api right, I'm not in 4 of those rooms....

We known that [correctly computing unread counts in an E2EE environment is not fully possible backend side](https://github.com/matrix-org/matrix-spec-proposals/pull/4076) and plan on tackling that client side but in the meantime whatever counts we do have should work predictably.

Main tracking ticket Element X side: https://github.com/element-hq/element-x-ios/issues/2066

Other potentially related tickets:
- https://github.com/element-hq/synapse/issues/15698
- https://github.com/element-hq/synapse/issues/1115

**Comment by benbz** [comment]
> Most recent conversation around this happened starting [here](https://matrix.to/#/!PYmTIzCXFFOiozouAk:matrix.org/$fR4fXAFYHQfOSPhXoQNP-2-BppiVQ6fy40FB6RgIqlY?via=matrix.org&via=element.io&via=one.ems.host) where Ben found that
> 
> > I've got a 5 stuck on my EI and looking at `event_push_summary` I've got 5 rows for 5 different rooms with notif_count=1 (no rows in `event_push_actions` for those 5 room ids). If I'm driving the admin api right, I'm not in 4 of those rooms....

The 4 rooms I was not in appeared to be rejected invites. I could not reproduce a stuck badge on EI by rejecting test invites from other accounts I control, though I still gained rows in `event_push_summary` with `notif_count=1` for those rejected invites. I didn't get further as to investigating what was different between my test rejected invites and the prior 4 that did contribute towards a stuck badge

**Comment by clokep** [comment]
If we think this is new, maybe a regression from #16756?

**Comment by ara4n** [comment]
it could well be new - people really starting complaining most about it over the last month or so.

**Comment by jacotec** [comment]
Same here, all users are massively complaining about totally wrong unread badges, me included. Definitively related to updating Synapse from .98 to .101.

Also the wrong batch is synced to all devices which points also to the server side.

Hope this will be fixed more sooner than later, it's pretty bad to not see if there are new messages anymore.

**Comment by wrjlewis** [comment]
Related [PR](https://github.com/element-hq/synapse/pull/16927)

**Comment by morguldir** [comment]
Can confirm it’s new, also easily reproducable with invites, each one bumps the notification count by one, even if you accept/decline/leave.

It’s happening in Fluffychat iOS as well, and i think it’s more noticable on iOS since the client can’t just ignore the server counts

**Comment by jacotec** [comment]
@wrjlewis Do you think the PR you've mentioned will fix it?

**Comment by wrjlewis** [comment]
> @wrjlewis Do you think the PR you've mentioned will fix it?

Sorry no, I've striked out that comment, we haven't fixed this yet.

**Comment by jacotec** [comment]
> > @wrjlewis Do you think the PR you've mentioned will fix it?
> 
> Sorry no, I've striked out that comment, we haven't fixed this yet, but investigating

Oh, what a pity :-(

Was there a database update, or can I go back to 1.098 without issues? The impact of this bug is unfortunately massive.

**Comment by wrjlewis** [comment]
> > > @wrjlewis Do you think the PR you've mentioned will fix it?
> > 
> > 
> > Sorry no, I've striked out that comment, we haven't fixed this yet, but investigating
> 
> Oh, what a pity :-(
> 
> Was there a database update, or can I go back to 1.098 without issues? The impact of this bug is unfortunately massive.

There hasn't been any schema migrations since v1.96.0 so you can roll back safely 👍. 

For future reference, you can check [here](https://element-hq.github.io/synapse/latest/upgrade.html#rolling-back-to-older-versions) to see which versions are compatible when rolling back. 

We're continuing to investigate the badge count issue and want to fix this asap

**Comment by anoadragon453** [comment]
https://github.com/element-hq/synapse/pull/16954 should help with @benbz's case of having notifications for rooms that he's left. However @morguldir [reported in TWIM](https://matrix.to/#/!QQpfJfZvqxbCfeDgCj:matrix.org/$lt-791yuezkG6heLXKxMXPk8cLVjO5gL2nfQhq8sfuE?via=matrix.org&via=envs.net&via=mozilla.org) that they're still seeing more notification counts than expected:

> Haven’t tried the PR, but the count goes up for me even if i accept the invite, and it goes up by 2 when i first receive it 🤔

**Comment by qbit** [comment]
> #16954 should help with @benbz's case of having notifications for rooms that he's left. However @morguldir [reported in TWIM](https://matrix.to/#/!QQpfJfZvqxbCfeDgCj:matrix.org/$lt-791yuezkG6heLXKxMXPk8cLVjO5gL2nfQhq8sfuE?via=matrix.org&via=envs.net&via=mozilla.org) that they're still seeing more notification counts than expected:
> 
> > Haven’t tried the PR, but the count goes up for me even if i accept the invite, and it goes up by 2 when i first receive it 🤔


This cleared a number of stuck notifications for me \o/. Still have one coming from something..

**Comment by anoadragon453** [comment]
https://github.com/element-hq/synapse/pull/16954 is a fix that partially helps the issue that we've identified (with @morguldir's help!) that is caused by https://github.com/element-hq/synapse/pull/16756 (included since v1.100.0). That fix is currently on `release-v1.102` and went out in v1.102.0rc1.

Given that https://github.com/element-hq/synapse/pull/16954 is only a partial fix, and users are still seeing buggy notification counts, I think it best to revert https://github.com/element-hq/synapse/pull/16756 (and its performance gains), as well as the partial fix, on the `release-v1.102` branch. This would give us working notifications again for v1.102.0.

We can aim to reintroduce https://github.com/element-hq/synapse/pull/16756 in a later release once the known bugs have been worked out.

**Comment by jacotec** [comment]
Sounds like a plan! Downgrading to 1.98 fixed it immediately for me (this issue was a real showstopper for me and my users), I'm happy to get back on track once this is solved.

**Comment by itsthejb** [comment]
Hi all,

Have also been seeing this issue, so also reverted to `matrixdotorg/synapse:v1.98.0`. Works just fine. I'll wait out the full fix and then go back to `latest`

**Comment by anoadragon453** [comment]
Synapse v1.102.0 has been released with https://github.com/element-hq/synapse/pull/16756 reverted. Notification counts should be fixed.

Thanks to everyone who helped track down the issue! We'll have a fixed version of https://github.com/element-hq/synapse/pull/16756 out in a later release.

**Comment by bstaeheli** [comment]
We're on synapse v1.104.0 and still have this problems. On Fluffy Chat and Element X on iOS, but not on the "classic" Element Client on our Desktops.
