### ISSUE TITLE
Abnormal logging from worker_lock.py

### ISSUE THREAD

**Issue by raphaelbadawi** [element-hq/synapse#18221]
### Description

Hello there,

Some history behind the issue. We were using Synapse 1.98, and to avoid flooding from the presence feature, [we applied this patch from this issue](https://github.com/element-hq/synapse/issues/16843#issuecomment-2007807574) and this worked well.

Recently we updated to Synapse 1.125 and the presence change storm came back. Since rate-limit was implemented in Synapse 1.124, we removed our patch to rely on the new mechanism. While being flooded, we noticed that the consequences of the issue were worse than 18 months ago since it now crashes the entire server.

In the logs we noticed something new, logs like this :

`2025-03-07 09:25:54,626 - root - 274 - WARNING - sentinel - Lock timeout is getting excessive: 747219185633533129613811404156259233971089331878494532580210173424746711084791089106082450955110608529191362653363165049891653914480755326168880379598947624597795819941201301722130188899194899188406241147079660310783397469716735872037991981377152862739140111812744262910064693812209876190943167529751342311021438043008766494386184259979355506403995836956665016959707590206415293601926385161774355252449900571232800892433503149036264336316069226081064285531353458681141174508391246376982247773496285591867121965950286134644640781796594767551542605817732736086479589950474537245937452620560279516506111800408344608704247581899721751284963506571721030207915157769086556621383347464138459152826527440828307470515494751150272907296532529180932330417382199017641281341938894247873084044949264513586530791715776157195864081695865474525857847622644476407492952918516142914929136797578388466774197963183523845956350122335878508129342025334156666552054326202550326485043561191351799892551223711961528027686644480218096762732291965060003061050028033335872339112405294435751639772818803451177588066926898761434627234487776464285349768365706382064791455203309929994154976493584140472710746933861949542801661630756263198164990225539326611874898302760099838901970968596141391648096727535495503897979803080672024027459912704362578416176911635397757139964739357038277851585728666776895373765608570647686093473887308201039142657940120297326956049882822960502454146283788858787588946385242858784617533056316840416022802656062667216587906480699108353098466195511463041051980606728234595368633567054652240515183387619626712437486142060904412242208068073853349370190349996437020917874281874472449309457533001115061932946571257993872151716476965154380052158271761367515928848363670361536804997687046238888318189890904565417990783522062983779886083495162425327856299635772197082120679631818500477576148326700659966608263667536127973810200161576847547909210584488635238169514578824197102334699499850271788619662231511157880598626061015924144894732401615621048000940137900441781917214112907301246928668644754020326849970793393644133655431868844779408488531743147107928212140321119728600694934961986174451590811475349509285023725593029583713348770303758571147680603011472587785179189642925094732465784568894329378358171617130496801135984837964087019951017442976575063637917851931663233704807776385333953560830251511622299846466485700728652105643881807497353915555948896111037116287626148541731716755278088886709216185081733693593143846299786623744861263510060101479838004698863937642591585510624962890110914495234927458425690031665268865820106811281692028642365755300516005299655933904736160288065523583867888095499126376994279388156945594517570997481903250147699316666884004524181778850203923086527069856639969458336830856557035167315582885378566579015236025670281086122217638433805035789671710740252287834361079927478829034217608879097774080s. There may be a deadlock.`

We saw this logging was introduced in worker_lock.py 3 weeks ago, but the figures for a retry interval seem abnormal.

What can cause those insanes figures in the worker locks?

### Steps to reproduce

- have multiple users using the service with multiple devices at the same time

- see the flood happen

- check the logs for the weird entries

### Homeserver

Hosted homeserver

### Synapse Version

1.125

### Installation Method

Docker (matrixdotorg/synapse)

### Database

PostgreSQL 15

### Workers

Single process

### Platform

Containers running on an AlmaLinux 9 host.

### Relevant log output

```shell
2025-03-07 09:25:54,626 - root - 274 - WARNING - sentinel - Lock timeout is getting excessive: 747219185633533129613811404156259233971089331878494532580210173424746711084791089106082450955110608529191362653363165049891653914480755326168880379598947624597795819941201301722130188899194899188406241147079660310783397469716735872037991981377152862739140111812744262910064693812209876190943167529751342311021438043008766494386184259979355506403995836956665016959707590206415293601926385161774355252449900571232800892433503149036264336316069226081064285531353458681141174508391246376982247773496285591867121965950286134644640781796594767551542605817732736086479589950474537245937452620560279516506111800408344608704247581899721751284963506571721030207915157769086556621383347464138459152826527440828307470515494751150272907296532529180932330417382199017641281341938894247873084044949264513586530791715776157195864081695865474525857847622644476407492952918516142914929136797578388466774197963183523845956350122335878508129342025334156666552054326202550326485043561191351799892551223711961528027686644480218096762732291965060003061050028033335872339112405294435751639772818803451177588066926898761434627234487776464285349768365706382064791455203309929994154976493584140472710746933861949542801661630756263198164990225539326611874898302760099838901970968596141391648096727535495503897979803080672024027459912704362578416176911635397757139964739357038277851585728666776895373765608570647686093473887308201039142657940120297326956049882822960502454146283788858787588946385242858784617533056316840416022802656062667216587906480699108353098466195511463041051980606728234595368633567054652240515183387619626712437486142060904412242208068073853349370190349996437020917874281874472449309457533001115061932946571257993872151716476965154380052158271761367515928848363670361536804997687046238888318189890904565417990783522062983779886083495162425327856299635772197082120679631818500477576148326700659966608263667536127973810200161576847547909210584488635238169514578824197102334699499850271788619662231511157880598626061015924144894732401615621048000940137900441781917214112907301246928668644754020326849970793393644133655431868844779408488531743147107928212140321119728600694934961986174451590811475349509285023725593029583713348770303758571147680603011472587785179189642925094732465784568894329378358171617130496801135984837964087019951017442976575063637917851931663233704807776385333953560830251511622299846466485700728652105643881807497353915555948896111037116287626148541731716755278088886709216185081733693593143846299786623744861263510060101479838004698863937642591585510624962890110914495234927458425690031665268865820106811281692028642365755300516005299655933904736160288065523583867888095499126376994279388156945594517570997481903250147699316666884004524181778850203923086527069856639969458336830856557035167315582885378566579015236025670281086122217638433805035789671710740252287834361079927478829034217608879097774080s. There may be a deadlock.
```

### Anything else that would be useful to know?

Glimpses of the logging here:

https://github.com/user-attachments/assets/fca07c28-d7dc-44eb-86ac-f8dd2a234ea8

**Comment by lamoboos223** [comment]
can you connect to new db and confirm if the issue still exists? @raphaelbadawi

**Comment by jlemangarin** [comment]
Hello @lamoboos223, I don't know what means new db but I can confirm I accidentally removed the patch a few days ago and the homeserver crashed with this issue just a few hours after.

After further investigations on our side, it seems more related to encryption key system rather than presence system, but @raphaelbadawi will be able to tell you more about that

**Comment by raphaelbadawi** [comment]
Hello,

Yes it was very weird, from what I understood, in _upload_one_time_keys_for_user in e2e_keys.py, Synapse returns 400 if a duplicate key request is detected.

What I believe happened in the following: in our platform, a user may use Element in multiple tabs with the same device ID. What happens them is that request from those tabs are detected as duplicate requests, so the server replies 400, but Element then keeps trying to upload the 4S key, and it never ends. And during this time, locks acquiring are accumulating, until the server finally breaks.

Replacing the 400 response by a raw return actually fixed the thing on our side.

**Comment by f0x52** [comment]
```
root: [sentinel] Lock timeout is getting excessive: 5109025633255901406490603201282467173533213109178216723586384091310221706374019570115214739379249686341764459677671979805111696195013249418629486004215987448164939245170247861515869531980557965468409447395980627190882522776270279446130094624176920305618040414321006033153354120329695285099202720472444929656181837347211788777862783305420499003549343118920583775222224081172638653662150123332248351032269485179945740060063307140926730099593534936551574588302070375076969240544892555384208145951224644865841059873169230402514745212748572987171541714953714265864266424503037481344364114706071636320697977602885803010884413691575446875190706356615999423193137180359186272263362454580420442013775939400128960085497674817076619563237924324875974268528385648620104534055468415443784058009858228345489494916056337722233021545250906421133253507254512844021998731120291572306799402188312472719250107200829054679903434028222777484042502068452376021705049029176092047922850051621239884173948564077284725655675779882339712775051765418395202113066102904730893621133384371994516292064091335945850560079231021779256473409958924593829658753748408781572474755248908995411692972421160284053099605117776786462294994056768520405567823193546936393003447796856902308552336666531318357064462706584175120309908094943699741350444150925854836855651519036024744217014872673930388303941792699204625762364366576200125831739045183341894826147091302355040689143072732890451983742222917189597521245434034093139703835897061323943034218353552006503011070252735168774082893051419517515586551565528292518673044498493395066371422814072853649645788659427222179417160967322835389563299334485373578875846950428780687287121292994074784150785169263980641727546923784402044699462160421144626382033818628916887926491820225379211583008862828393676541735929226085191557386142980985455043068148173039028927320815873426443582946428077123113325719446991576536948258476541490261205398007023740034162240092157661737009990747425908130322914427205727302582074300511591162812805311503933544244350111487731891128251160001066361972537652823541042344521139325701659209766427771757203142677064691750804518241420310646628376954896104784973221629880335794649159753514408171211641964519672633035086459940674813921645702257248916027536112769630776299444874042540708311652975164614344121630192736186906021658804020617515332080910394884321733463623130202237405801168606384903890041017876188650839247248628526009071656130966674690974026077983392837131633995351018884852928014580906799227869504672185404269568062565885967910836232759296009826970094935882409389447548386021544323389352601160508537154852794049491050915932893430995835515984281683450632424771747997244080316093371521870780585117426455919906675509582644312186749482609755574747130768418071178757731854719127114668162866824760555356846290937880487929784749349238322879262597930268552721988870121020453343420342736782708422444307475186454245589875596444401150145218556000665761834879731715688434108803577066580726116411717723736950603034105617020909531420610544168940834736112266324647184633108730868971929497240156054827709653777064766212172872103816145415652733589994563952260449793556616819302662227033271118223836791608951528945208970603736199651496476510582247794772833246739103523629288575785935292057207665167923340388153705271198628568501518387955976615202216884187520839766728224464007569137308996720026745753710450203334947688688626510675569820336145831681848588501390164326306501326265206654088794993978037004244063855171561886712354541944709218386608420090557080692131234729571715396552723224379934949605211855715489895266986502565840593001827303968468871212078889417740327858798386185489457272776892744934298741151637915931126099755636896616937909626801997484801373791726463435793895891863406882590636650311367096024864562434667946825083148848128028872979154347847695771674187024729296359910248953102843532887063342012963591815890716441838892777297089927370533105837075649351212725397350554496605164251272988502891200797388637461739319871555869595478255495263203858086161074524404789682945678530523328159819527728886915759129376788775239093419402674671215064273287879949203348413701251103654939284301197276048438396978199712043708146779024681532998268880991427324067653677654619787666139381760s. There may be a deadlock.
```
Seem excessive indeed, given the age of the universe is estimated to be 4e17 seconds, and this is 5e4299

**Comment by jlemangarin** [comment]
@f0x52 Btw if you're interested, we temporarily made a fix preventing the issue, waiting for it to be fixed

```
# CEO-Vision synapse patch: GOFAST-12760 Avoid duplicate requests on SSSS key upload (occurring with same device on multiple tabs)
RUN sed -i "/if not _one_time_keys_match(ex_json, key):/,/^                        )$/c\                    return" /opt/synapse/env/lib64/python3.9/site-packages/synapse/handlers/e2e_keys.py
```

That will absolutely not be the final patch for sure, just preventing productions to crash ;)

**Comment by f0x52** [comment]
I think the issue title should be updated to reflect that this completely freezes the synapse main process, effectively breaking the homeserver until SIGKILL'ed (does not even exit on SIGTERM)

**Comment by reivilibre** [comment]
I believe this should be fixed since https://github.com/element-hq/synapse/pull/18543

**Comment by green5-zero** [comment]
> I believe this should be fixed since [#18543](https://github.com/element-hq/synapse/pull/18543) @reivilibre please reopen.

Not fixed, happening still in the latest version as of 6 days ago, and it floods the log file once the daemon locks up completely, inflating it to hundreds of MB in seconds. (Because of this I have since deleted the logs that show this happening.)

It's caused by a bad session, deleting this session seems to have fixed the problem. The session is listed just before some of the timeouts so it is clear which session is the issue. This is still a very important issue to solve since a bad actor can essentially DoS a homeserver with this if they are able to reproduce creating a bad session.

According to the user with the bad session (using cinny), they lost the local keys for it.

I have this one screenshot still, for anyone encountering the issue:

<img width="1896" height="433" alt="Image" src="https://github.com/user-attachments/assets/c0bbc38c-70cf-4adc-8194-6bb0adb534d3" />

**Comment by vincib** [comment]
I just had the same with synapse 1.144, 2 days ago and today

in both cases a new key seems to be the culprit : 

```
2025-12-17 17:03:26,356 - synapse.handlers.e2e_keys - 955 - INFO - POST-61150 - Adding one_time_keys dict_keys(['signed_curve25519:AAAAAAAAAXX']) for device 'XXXXXXXX' for user '@user:domain.host' at 1765987406352
2025-12-17 17:03:26,358 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 351843720888320s. There may be a deadlock.
2025-12-17 17:03:26,358 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 703687441776640s. There may be a deadlock.
2025-12-17 17:03:26,358 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 1407374883553280s. There may be a deadlock.
2025-12-17 17:03:26,359 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 2814749767106560s. There may be a deadlock.
2025-12-17 17:03:26,359 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 5629499534213120s. There may be a deadlock.
2025-12-17 17:03:26,359 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 11258999068426240s. There may be a deadlock.
2025-12-17 17:03:26,359 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 22517998136852480s. There may be a deadlock.
2025-12-17 17:03:26,359 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 45035996273704960s. There may be a deadlock.
2025-12-17 17:03:26,359 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 90071992547409920s. There may be a deadlock.
2025-12-17 17:03:26,359 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 180143985094819840s. There may be a deadlock.
2025-12-17 17:03:26,360 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 360287970189639680s. There may be a deadlock.
2025-12-17 17:03:26,360 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 720575940379279360s. There may be a deadlock.
2025-12-17 17:03:26,360 - synapse.handlers.worker_lock - 280 - WARNING - sentinel - Lock timeout is getting excessive: 1441151880758558720s. There may be a deadlock.

**Comment by richvdh** [comment]
Seems like this turned into https://github.com/element-hq/synapse/issues/19315 / https://github.com/element-hq/synapse/issues/19588
