### ISSUE TITLE
synapse sends outbound federation containing non-canonical json, *blocking all future federation attempts if the remote server rejects it*

### ISSUE THREAD

**Issue by tusooa** [element-hq/synapse#18554]
### Description

Twin of https://github.com/matrix-construct/tuwunel/issues/68

A server (synapse 1.127.1) sends out the following PUT /_matrix/federation/v1/send/ request

```
{"origin":"neo.angry.im","origin_server_ts":1749956105872,"pdus":[{"auth_events":["$vBJzDMoU3vE-7hVDchhnoS1Zrp-E2fjzLswEb032pFs","$Z5HM7oRhsAgJdE4ICGoc8W73IbaU2ARqcl4Zcx2eGs0","$JLV8VUdP7SU8Y2wijz5r-BlC_9qK-gfG7kFXZ880zUg"],"content":{"body":"i can still sometimes trigger this overlapping monitor arrangement when enabling laptop screen. this is on 6.4 beta","m.mentions":{},"msgtype":"m.text"},"depth":9007199254741000,"hashes":{"sha256":"Et0dWuy/hQEPzGWFtxs9JVLj20Wz7TGHfqp2Kx62XhY"},"origin":"neo.angry.im","origin_server_ts":1747401139654,"prev_events":["$BjylZqhe_ZX7BCJBUnrWENf6KbYYGuztkJ8_A7i5PNE"],"room_id":"!xdwRmYgjAuZSEhsheE:kde.org","sender":"@caiye:neo.angry.im","signatures":{"neo.angry.im":{"ed25519:a_ZOqa":"yNR8Z1pX7jzVhVKCaHOxFYuXfCmSd1xUYxwBT87W56hpa14uRcrvWeCUPMY0aCC8+Igu8ehD++onu/EXSa+ECQ"}},"type":"m.room.message","unsigned":{"age_ts":1747401139654}}]}
```

9007199254741000 is beyond the safe int range 2**53 - 1 required in https://spec.matrix.org/v1.14/appendices/#canonical-json , probably causing the request to be rejected by conduwuit (tuwunel).

**Furthermore, synapse seems to be unwilling to go beyond this particular event, and send it again and again, even though there are other events in other rooms that should be federated.**

### Steps to reproduce

I don't know how to reproduce this.

### Homeserver

neo.angry.im

### Synapse Version

{"server":{"name":"Synapse","version":"1.127.1 (b=master,t=v1.127.1,ecc09b15f1)"}}

### Installation Method

I don't know

### Database

Don't know

### Workers

I don't know

### Platform

Don't know

### Relevant log output

```shell
Don't know
```

**Comment by spaetz** [comment]
Fixed in v130 by https://github.com/element-hq/synapse/pull/18447

**Comment by tusooa** [comment]
Um, it seems that the problem is not fixed. neo.angry.im upgraded to 1.132.0, but it is still trying to send that same PDU to me.

**Comment by kegsay** [comment]
Confusingly, canonical JSON checks were not enforced until [v6](https://spec.matrix.org/unstable/rooms/v6/#canonical-json). This means whether `/send` is sending canonical JSON _depends on the data in the request body_. If the event is in a room < v6 then `/send` requests involving that room may fail canonical JSON checks.

The room `!xdwRmYgjAuZSEhsheE:kde.org` however is running v7, so in theory this **should** be applying canonical JSON checks.

**Comment by kegsay** [comment]
I think this was just forgotten when [serialize_and_filter_pdus](https://github.com/element-hq/synapse/blob/develop/synapse/federation/units.py#L130) was added. All the callers of that function are in `federation_server.py`, which is not where the `/send` code lives. Notably, I don't see this function being called [here](https://github.com/element-hq/synapse/blob/develop/synapse/federation/sender/transaction_manager.py#L121) where we make the /send transaction.

**Comment by tusooa** [comment]
@kegsay I care more about why synapse insists on the attempt to deliver that single PDU, and completely ignores the other events in other rooms or to-device messages. That seems to be a deeper problem.

**Comment by kegsay** [comment]
Most likely because it's queue based. I'm not familiar with that part of the code unfortunately.
